// Renders a brand guideline (built by brandGuideline.js) as a polished,
// print-ready PDF — cover, palette, typography, and usage-rules pages —
// using jsPDF's vector drawing. Runs entirely in the browser, no server,
// no API key.

const PAGE_W = 210; // A4, mm
const PAGE_H = 297;
const MARGIN = 20;

const INK = [26, 22, 18];
const INK2 = [96, 88, 80];
const INK3 = [150, 142, 134];
const LINE = [226, 220, 212];
const PAPER = [252, 250, 247];

function hexToRgb(hex) {
  const clean = hex.replace('#', '');
  const n = parseInt(clean, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function tracked(text, spacing = 0.4) {
  return text.toUpperCase().split('').join(String.fromCharCode(8202).repeat(Math.round(spacing * 3)));
}

function newPage(doc) {
  doc.addPage();
  doc.setFillColor(...PAPER);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
}

function sectionHeader(doc, kicker, title, accentRgb) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...accentRgb);
  doc.text(tracked(kicker), MARGIN, MARGIN);
  doc.setDrawColor(...accentRgb);
  doc.setLineWidth(0.8);
  doc.line(MARGIN, MARGIN + 3, MARGIN + 14, MARGIN + 3);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...INK);
  doc.text(title, MARGIN, MARGIN + 15);
}

function footer(doc, pageLabel, brandName) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...INK3);
  doc.text(brandName, MARGIN, PAGE_H - 12);
  doc.text(pageLabel, PAGE_W - MARGIN, PAGE_H - 12, { align: 'right' });
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, PAGE_H - 16, PAGE_W - MARGIN, PAGE_H - 16);
}

function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(text, maxWidth);
}

async function dataUrlDimensions(dataUrl) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = reject;
    img.src = dataUrl;
  });
}

function imageFormatFromDataUrl(dataUrl) {
  const match = /^data:image\/(\w+);/.exec(dataUrl);
  const type = (match?.[1] || 'png').toLowerCase();
  if (type === 'jpg') return 'JPEG';
  return type.toUpperCase();
}

export async function generateBrandGuidelinePdf({ guideline, brandName, logoDataUrl }) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const accentRgb = hexToRgb(guideline.palette[0]?.hex || '#8a6dfa');
  const name = brandName?.trim() || 'Brand';

  // ---------- Cover ----------
  doc.setFillColor(...PAPER);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
  doc.setFillColor(...accentRgb);
  doc.rect(0, 0, PAGE_W, 6, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...accentRgb);
  doc.text(tracked('Brand Guideline', 0.6), MARGIN, 40);

  if (logoDataUrl) {
    try {
      const { width, height } = await dataUrlDimensions(logoDataUrl);
      const boxSize = 60;
      const scale = Math.min(boxSize / width, boxSize / height);
      const w = width * scale;
      const h = height * scale;
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(MARGIN, 55, boxSize + 20, boxSize + 20, 4, 4, 'F');
      doc.setDrawColor(...LINE);
      doc.roundedRect(MARGIN, 55, boxSize + 20, boxSize + 20, 4, 4, 'S');
      doc.addImage(
        logoDataUrl,
        imageFormatFromDataUrl(logoDataUrl),
        MARGIN + 10 + (boxSize - w) / 2,
        55 + 10 + (boxSize - h) / 2,
        w,
        h
      );
    } catch {
      // if the logo can't be decoded, just skip the image — text cover still works
    }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(34);
  doc.setTextColor(...INK);
  doc.text(name, MARGIN, 160);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11.5);
  doc.setTextColor(...INK2);
  const coverLines = wrapText(doc, guideline.summary, PAGE_W - MARGIN * 2);
  doc.text(coverLines, MARGIN, 172);

  // palette strip along the bottom
  const stripY = PAGE_H - 40;
  const swatchW = (PAGE_W - MARGIN * 2) / Math.max(1, guideline.palette.length);
  guideline.palette.forEach((p, i) => {
    doc.setFillColor(...hexToRgb(p.hex));
    doc.rect(MARGIN + i * swatchW, stripY, swatchW, 14, 'F');
  });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...INK3);
  doc.text(`Generated by Studio Tracker — ${new Date().toLocaleDateString()}`, MARGIN, PAGE_H - 20);

  // ---------- Palette page ----------
  newPage(doc);
  sectionHeader(doc, 'Identity', 'Color Palette', accentRgb);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(...INK2);
  doc.text(
    wrapText(
      doc,
      'Pulled directly from your logo file. Use the primary color for the majority of brand surfaces, secondary as a support tone, and accents sparingly.',
      PAGE_W - MARGIN * 2
    ),
    MARGIN,
    46
  );

  let py = 62;
  guideline.palette.forEach((p) => {
    const rgb = hexToRgb(p.hex);
    doc.setFillColor(...rgb);
    doc.roundedRect(MARGIN, py, 34, 34, 3, 3, 'F');
    doc.setDrawColor(...LINE);
    doc.roundedRect(MARGIN, py, 34, 34, 3, 3, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...INK);
    doc.text(p.role, MARGIN + 42, py + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...INK2);
    doc.text(`${p.hex.toUpperCase()}  ·  RGB ${rgb.join(', ')}  ·  ${p.share}% of the mark`, MARGIN + 42, py + 18);

    py += 42;
  });

  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, py + 4, PAGE_W - MARGIN, py + 4);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(...INK2);
  doc.text(wrapText(doc, guideline.backgroundNote, PAGE_W - MARGIN * 2), MARGIN, py + 14);

  footer(doc, '02', name);

  // ---------- Typography page ----------
  newPage(doc);
  sectionHeader(doc, 'Identity', 'Typography', accentRgb);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(64);
  doc.setTextColor(...INK);
  doc.text('Aa', MARGIN, 90);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...INK2);
  doc.text('Headings', MARGIN, 100);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...accentRgb);
  doc.text(guideline.typography.heading, MARGIN, 108);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(40);
  doc.setTextColor(...INK);
  doc.text('Aa', MARGIN + 90, 90);
  doc.setFontSize(11);
  doc.setTextColor(...INK2);
  doc.text('Body text', MARGIN + 90, 100);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...accentRgb);
  doc.text(guideline.typography.body, MARGIN + 90, 108);

  doc.setDrawColor(...LINE);
  doc.line(MARGIN, 122, PAGE_W - MARGIN, 122);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...INK2);
  doc.text(wrapText(doc, guideline.typography.mood, PAGE_W - MARGIN * 2), MARGIN, 134);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(...INK3);
  doc.text(
    wrapText(
      doc,
      'Suggested pairing, not extracted from your file — free tools can’t read fonts out of a flattened logo image. Both are free on Google Fonts.',
      PAGE_W - MARGIN * 2
    ),
    MARGIN,
    148
  );

  footer(doc, '03', name);

  // ---------- Usage page ----------
  newPage(doc);
  sectionHeader(doc, 'Application', 'Logo Usage', accentRgb);

  // clear space diagram
  const boxX = MARGIN;
  const boxY = 46;
  const boxSize = 46;
  const pad = 10;
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.4);
  doc.setLineDashPattern([1.2, 1.2], 0);
  doc.rect(boxX, boxY, boxSize + pad * 2, boxSize + pad * 2, 'S');
  doc.setLineDashPattern([], 0);
  doc.setFillColor(...accentRgb);
  doc.roundedRect(boxX + pad, boxY + pad, boxSize, boxSize, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text('LOGO', boxX + pad + boxSize / 2, boxY + pad + boxSize / 2, { align: 'center', baseline: 'middle' });

  const textX = boxX + boxSize + pad * 2 + 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...INK);
  doc.text('Clear space', textX, boxY + 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...INK2);
  doc.text(wrapText(doc, guideline.clearSpace, PAGE_W - MARGIN - textX), textX, boxY + 22);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...INK);
  doc.text('Minimum size', textX, boxY + 52);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...INK2);
  doc.text(wrapText(doc, guideline.minSize, PAGE_W - MARGIN - textX), textX, boxY + 60);

  let dy = boxY + boxSize + pad * 2 + 18;
  const colW = (PAGE_W - MARGIN * 2 - 10) / 2;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(34, 130, 90);
  doc.text('DO', MARGIN, dy);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(190, 70, 60);
  doc.text("DON'T", MARGIN + colW + 10, dy);
  dy += 8;

  const startDy = dy;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...INK2);
  let doY = startDy;
  guideline.dos.forEach((d) => {
    doc.setTextColor(34, 130, 90);
    doc.text('+', MARGIN, doY);
    doc.setTextColor(...INK2);
    const lines = wrapText(doc, d, colW - 6);
    doc.text(lines, MARGIN + 6, doY);
    doY += lines.length * 5 + 4;
  });

  let dontY = startDy;
  guideline.donts.forEach((d) => {
    doc.setTextColor(190, 70, 60);
    doc.text('–', MARGIN + colW + 10, dontY);
    doc.setTextColor(...INK2);
    const lines = wrapText(doc, d, colW - 6);
    doc.text(lines, MARGIN + colW + 16, dontY);
    dontY += lines.length * 5 + 4;
  });

  footer(doc, '04', name);

  return doc;
}

export async function downloadBrandGuidelinePdf(opts) {
  const doc = await generateBrandGuidelinePdf(opts);
  const safeName = (opts.brandName || 'brand').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  doc.save(`${safeName}-brand-guideline.pdf`);
}
